module.exports = {
    'index': {},
    'recovery-password': { path: '/users/recovery-password/:key' },
    'activate-profile': { path: '/users/activate-profile/:key' },
    'account': { controller: 'UsersController', action: 'account' },
    'welcome': { controller: 'UsersController', action: 'welcome' },
    'sign-up': { controller: 'UsersController', action: 'sign-up' },
    'terms-and-conditions': { controller: 'UsersController', action: 'terms-and-conditions' },
    "change-password": { controller: 'UsersController', action: 'change-password', path: "/account/change-password"},
    "forgot-password": { controller: 'UsersController', action: 'forgot-password' },
    "forgot-password-sent": { controller: 'UsersController', action: 'forgot-password-sent' },
    "forgot-username": { controller: 'UsersController', action: 'forgot-username' },
    "forgot-username-sent": { controller: 'UsersController', action: 'forgot-username-sent' },
    "change-picture": { controller: 'UsersController', action: 'change-picture', path: "/account/change-picture"},
    "delete-picture": { controller: 'UsersController', action: 'delete-picture', path: "/account/delete-picture"},
    "delete-account": { controller: 'UsersController', action: 'delete-account', path: "/account/delete-account"},
    "create-group": { controller: 'GroupsController', action: 'create', path: "/groups/create" },
    "groups": { controller: 'GroupsController', action: 'groups' },
    "messages": { controller: 'MessagesController', action: 'messages' },
    "messagesUser": { controller: 'MessagesController', action: 'messagesUser', path: '/messages/:key' },
    "send-message": { controller: 'MessagesController', action: 'send-message', path: '/send-message' },
    "send-message-file": { controller: 'MessagesController', action: 'send-message-file', path: '/send-message/:key' },
    "rate-message": { controller: 'MessagesController', action: 'rate', path: '/messages/rate/:id/:type' },
    "invite-lists": { controller: 'InviteListsController', action: 'invite-lists' },
    "faq": { controller: 'FaqController', action: 'index' ,path: "/faq" },
    "feedback": { controller: 'FeedbackController', action: 'index' ,path: "/feedback" },
    "feedback-submit": { controller: 'FeedbackController', action: 'feedback' ,path: "/post-feedback" },
    "vote-subscribe": { controller: 'VoteController', action: 'subscribe', path: '/vote/subscribe' },
    "vote-respond": { controller: 'VoteController', action: 'respond', path: '/vote/respond/:for' },
    "vote-spam": { controller: 'VoteController', action: 'spam', path: '/vote/spam/:id' },
    "vote": { controller: 'VoteController', action: 'main', path: '/vote/:for' },
    "archives": { controller: 'ArchivesController', action: 'index', path: '/archives' },
    "archive-single": { controller: 'ArchivesController', action: 'single', path: '/archives/:id' },
    "send-invitations": { controller: 'GroupsController', action: 'sendInvitations', path: '/groups/invite' },
    "organize": { controller: 'GroupCategoriesController', action: 'index', path: '/organize' },
    "category-create": { controller: 'GroupCategoriesController', action: 'create', path: '/category/create' },
    "category-reorder": { controller: 'GroupCategoriesController', action: 'reorder', path: '/category/reorder' },
    "private-chat-add": { controller: 'PrivateChatsController', action: 'userAdd', path: '/private-chat/user-add' },
    "create-invite-list": { controller: 'InviteListsController', action: 'create', path: '/invite-list/create' },
    "edit-invite-list": { controller: 'InviteListsController', action: 'editInfo', path: '/invite-list/edit' },
    "remove-invite-list": { controller: 'InviteListsController', action: 'remove', path: '/invite-list/remove' },
    "subscribe-main-events": { controller: 'IndexController', action: 'subscribe', path: '/subscribe' },
    "get-notifications": { controller: 'IndexController', action: 'getNotifications', path: '/get-notifications' },
    "generic": [
        'users.recovery-password',
        'users',
        'users.login',
        'users.logout',
        'users.username-visibility',
        'users.name-visibility',
        'autocomplete.invitations',
        'search.users',
        'search.archives',
        'search.groups',
        'groups.join',
        'messages.chat-room',
        'messages.room'
    ]
};
// 'users.resend-activation-email',
